//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myPetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Record
    {
        public int IDRecord { get; set; }
        public int C_PetID { get; set; }
        public int C_DoctorID { get; set; }
        public System.DateTime C_date { get; set; }
        public string C_diagnosis { get; set; }
        public string C_treatment { get; set; }
    
        public virtual User User { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
