//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myPetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int IDMedication { get; set; }
        public int C_PetID { get; set; }
        public string C_medicationName { get; set; }
        public int C_dosage { get; set; }
        public int C_frequency { get; set; }
        public System.DateTime C_start { get; set; }
        public System.DateTime C_end { get; set; }
        public string C_notes { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
