//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myPetCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int IDMessage { get; set; }
        public int C_SenderID { get; set; }
        public int C_ReceiverID { get; set; }
        public string C_messageContent { get; set; }
        public System.DateTime C_timestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
